### ISSUE TITLE
New words: Functional Programming (FP)

### ISSUE THREAD

**Issue by iteles** [dwyl/technical-glossary#28]
Proposing this additional set of words.

# Tasks
+ [ ] Research definition for new words: Functional Programming (FP)
+ [ ] Add definition for new words: Functional Programming (FP)
+ [ ] Link to relevant example repos such as https://github.com/dwyl/learn-elm and/or https://github.com/dwyl/learn-elixir
