### ISSUE TITLE
Use Section Headings for Words for Linking

### ISSUE THREAD

**Issue by nelsonic** [dwyl/technical-glossary#42]
At present most of the terms in the glossary are defined as paragraphs where the word is bold:
https://github.com/dwyl/technical-glossary/blob/cc59df6bf2313e8df82ffcd8c93a3765099a54b2/README.md

![technical-glossary-not-headings](https://user-images.githubusercontent.com/194400/174282122-5e0d57e4-3c1e-4e92-984c-68f7feeba887.png)

That means we cannot [directly] link to a word or term from another document.
What I've done with the recent addition of the definition of "spike" 
is create a section heading for the word and then put the definition in a paragraph:
![image](https://user-images.githubusercontent.com/194400/174282505-dc0ee037-45a8-404c-8d9e-bb234a804fc5.png)

This allows us to link to it: https://github.com/dwyl/technical-glossary#spike

# Todo

+ [x] convert all terms to level 3 `###` headings in the `README.md` so that we can link to them.
+ [x] Add semantic line breaks https://sembr.org to all text for easy of reading/reviewing & maintaining.
  + [x] Put any links on their own line, again for easy of maintenance.
+ [x] Create PR to update!

**Comment by nelsonic** [comment]
Just going to put on some EDM (pace-setting music) and blitz through this 
so it's done and I don't have to think about it anymore.

**Comment by nelsonic** [comment]
Done: #43 ✅

**Comment by SimonLab** [comment]
#43 is now merged and we can close this issue
